### ISSUE TITLE
An error occurred when ROM connected to Splitter

### ISSUE THREAD

**Issue by Kugigi** [eugenelepekhin/LogicCircuit#7] opened 2022-07-22 08:33 UTC
it's my setting:
![1](https://user-images.githubusercontent.com/109789496/180393780-0a3df25a-015b-4294-9a2b-71a692d0346c.png)

issue:
![Snipaste_2022-07-22_16-01-20](https://user-images.githubusercontent.com/109789496/180393839-67f7b249-6b08-46f5-bdf7-961174b06ea7.png)

but it works if use Pin as the output:
![Snipaste_2022-07-22_16-02-01](https://user-images.githubusercontent.com/109789496/180393853-9c5f8596-ffe7-4db2-9fed-dd8b9f1072d7.png)

If I use it in a new Circuit, not error appear
![Snipaste_2022-07-22_16-19-15](https://user-images.githubusercontent.com/109789496/180396176-45ed3582-9de4-42d3-a98b-cbb436777251.png)

By the way, I have a file Created in September 2021 that not error appear At that time then and will show error now. Maybe only in the version after 2.22 ?

**Comment by eugenelepekhin** [comment] 2022-07-22 08:53
Hi,
This is optimization artifacts.
Your circuits on the first two pictures are not complete. You have ROM output connected to LEDs while input is connected to input pin which in turn does not connected anywhere. So, the input gets optimized away and hence your ROM input becomes unconnected when you power it up. Try to use these circuits on some other circuits and connect the input. It should work as you expected.

**Comment by Kugigi** [comment] 2022-07-22 09:06
OK, I understand. and thanks to answer

**Comment by eugenelepekhin** [comment] 2022-07-22 20:59
Closing as not a bug

**Comment by eugenelepekhin** [comment] 2022-07-22 20:59
Closing as not a bug

**Closed** 2022-07-22 20:59 UTC
